# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MGUtilsSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MGUtilsSwift
  pod 'Kingfisher', '~> 4.0'
  pod 'CLImagePickerTool', '~> 2.3.1'
  pod 'SwiftyJSON'
  pod 'ReachabilitySwift'
  pod 'Toast-Swift', '~> 3.0.1'

end
